### ISSUE TITLE
System Info not show

### ISSUE THREAD

**Issue by picchiosat** [dg9vh/MMDVMHost-Websocketboard#21]
After last commit not show System Info

**Comment by dg9vh** [comment]
What's in /var/log/syslog?

**Comment by picchiosat** [comment]
Feb 17 16:00:53 ir3ef python3[14986]: 2021-02-17 16:00:53,214 INFO Closed, remote=('79.6.136.177', 62353), path=/SYSINFO, exception=[Errno 13] Permission denied: '/tmp/mmdvm-version'

it is strange, I have 5 repeaters, 4 work fine and only one from this error. Before the commit they all worked

**Comment by dg9vh** [comment]
This seems to be a filesystem-problem with permissions for user "mmdvm"...

please check permission for /tmp-folder, maybe you should set chmod ugo+rw
/tmp so that every user can write to /tmp what is intended by nature of
this folder...

73

**Comment by dg9vh** [comment]
Do you have an read-only-overlay or something running at this installation?

I am wondering why the user can't write to this file... is it existing?
What does a ls -la /tmp/mmdvm-version show?

Otherwise: Did you put the user mmdvm as told in the readme.md into the
dialout-group? Think it is the problem that this installation the user
can't write/read from serial...

**Comment by picchiosat** [comment]
After reboot (I did not think about it) problem solved...
all work fine

73

**Comment by dg9vh** [comment]
Thank you - will close the issue then...

73 de Kim
